services:
  - type: web
    name: laravel-docker-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ''
    startCommand: ''
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: database-1.clmasqw6s8q7.eu-north-1.rds.amazonaws.com          # <-- CHANGE THIS
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: database-1        # <-- CHANGE THIS
      - key: DB_USERNAME
        value: admin       # <-- CHANGE THIS
      - key: DB_PASSWORD
        value: 0609$Appuas       # <-- CHANGE THIS
